apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: echo
              image: busybox
              command: ["echo", "This is a recurring job!"]
          restartPolicy: Never
